add_split_arch_project(
    NAME libaom
    GIT_REPOSITORY https://aomedia.googlesource.com/aom
    GIT_TAG v3.13.1
    GIT_SHALLOW ON

    CONFIGURE_COMMAND_X86
        ${CMAKE_COMMAND} -S <SOURCE_DIR> -B <BINARY_DIR>
        -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/install_x86
        -DAOM_TARGET_CPU=x86_64
        -DCMAKE_OSX_ARCHITECTURES=x86_64
        -DCMAKE_SYSTEM_PROCESSOR=x86_64
        -DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}
        -DENABLE_DOCS=OFF
        -DENABLE_EXAMPLES=OFF
        -DENABLE_TESTS=OFF
        -DENABLE_TOOLS=OFF
        -DBUILD_SHARED_LIBS=OFF
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        -DCMAKE_BUILD_TYPE=Release

    CONFIGURE_COMMAND_ARM
        ${CMAKE_COMMAND} -S <SOURCE_DIR> -B <BINARY_DIR>
        -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/install_arm
        -DAOM_TARGET_CPU=aarch64
        -DCMAKE_OSX_ARCHITECTURES=arm64
        -DCMAKE_SYSTEM_PROCESSOR=arm64
        -DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}
        -DENABLE_DOCS=OFF
        -DENABLE_EXAMPLES=OFF
        -DENABLE_TESTS=OFF
        -DENABLE_TOOLS=OFF
        -DBUILD_SHARED_LIBS=OFF
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        -DCMAKE_BUILD_TYPE=Release

    BUILD_COMMAND make -j${PROCESSOR_COUNT}
    INSTALL_COMMAND make install
)

create_lipo_target(libaom "libaom.a")
