ExternalProject_Add(libsdl3
    GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
    GIT_TAG main
    GIT_SHALLOW ON

    CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/install
        -DCMAKE_OSX_ARCHITECTURES=x86_64$<SEMICOLON>arm64
        -DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}
        -DSDL_SHARED=OFF
        -DSDL_STATIC=ON
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        -DSDL_GPU=OFF
        -DSDL_CAMERA=OFF
        -DSDL_JOYSTICK=OFF
        -DSDL_HAPTIC=OFF
        -DSDL_HIDAPI=OFF
        -DSDL_POWER=OFF
        -DSDL_SENSOR=OFF
        -DSDL_DIALOG=OFF
        -DSDL_DISKAUDIO=OFF
        -DSDL_DUMMYAUDIO=OFF
        -DSDL_DUMMYCAMERA=OFF
        -DSDL_DUMMYVIDEO=OFF
        -DSDL_OFFSCREEN=OFF
        -DSDL_RENDER_GPU=OFF
        -DSDL_TRAY=OFF
        -DSDL_VIRTUAL_JOYSTICK=OFF
        -DSDL_HIDAPI_LIBUSB=OFF
        -DSDL_HIDAPI_LIBUSB_SHARED=OFF
        -DSDL_TEST_LIBRARY=OFF
        -DSDL_COCOA=ON
    INSTALL_COMMAND make install
)
