ExternalProject_Add(libopus
    GIT_REPOSITORY https://github.com/xiph/opus.git
    GIT_TAG v1.6.1
    GIT_SHALLOW ON

    CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${CMAKE_BINARY_DIR}/install
        -DCMAKE_OSX_ARCHITECTURES=x86_64$<SEMICOLON>arm64
        -DCMAKE_OSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}
        -DBUILD_SHARED_LIBS=OFF
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
    INSTALL_COMMAND make install
)
